version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "vesak"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-8d17xhetx38z"
s3_prefix = "vesak"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

